app = "ac-refrigeration"
primary_region = "jnb"

[build]
  builder = "paketobuild"

[env]
  DJANGO_SETTINGS_MODULE = "config.settings"
  DEBUG = "False"
  ALLOWED_HOSTS = "ac-refrigeration.fly.dev"
  CORS_ORIGINS = "https://youracrepair.com"
  FRONTEND_URL = "https://youracrepair.com"
  DJANGO_SECRET_KEY = "r$i242zvzyblhca^s5%(4au5@($s4lz%+s(z3*_b(*kc+okh%@"
  COMPANY_PHONE = "0582618038"
  MONGODB_URI = "mongodb+srv://acrepairing21:<acrepairing21>@cluster786.eu651.mongodb.net/?appName=Cluster786"

[http_service]
  internal_port = 8000
  force_https = true

[processes]
  app = "gunicorn config.wsgi:application --bind 0.0.0.0:8000"

[deploy]
  strategy = "canary"
